import { ReactNode } from 'react';
import { Metadata } from 'next';
import './globals.scss';

/**
 * Metadata for the root layout
 */
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/**
 * Root layout component
 * @param {Object} props - The props for the RootLayout component
 * @param {React.ReactNode} props.children - The children to be rendered
 * @return {JSX.Element} The root layout component
 */
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
